#!/bin/sh

case "$1" in
    start)
        echo "Loading aesd-char-driver..."
        aesdchar_load
        ;;
    stop)
        echo "Unloading aesd-char-driver..."
        aesdchar_unload
        ;;
    *)
        echo "usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
